# name: "HTML5 build"
# on: push

# env:
#   GODOT_VERSION: 4.1
#   EXPORT_NAME: Gunner

# jobs:
#   export-HTML5:
#     name: HTML5 Export
#     runs-on: ubuntu-latest
#     container:
#       image: thebigg1/godot-ci:v4.1.stable.official_970459615
#     steps:
#       - name: Checkout
#         uses: actions/checkout@v2
#         with:
#           lfs: true
#       - name: Coding Style
#         run: |
#           gdformat -c Gunner/src
#       - name: Setup
#         run: |
#           mkdir -v -p ~/.local/share/godot/export_templates
#           mv /root/.local/share/godot/export_templates/${GODOT_VERSION}.stable ~/.local/share/godot/export_templates/${GODOT_VERSION}.stable
#       - name: HTML5 Build
#         run: |
#           mkdir -v -p build/HTML5
#           cd $EXPORT_NAME
#           godot --headless -v --export-debug "HTML5" ../build/HTML5/$EXPORT_NAME.html
#       # - name: zip html build
#       #   run: |
#       #     zip build/HTML5/$EXPORT_NAME.zip build/HTML5/*
#       # - name: Wrap inside redbean
#       #   run: |
#       #     chmod a+x /root/redbean.com
#       #     zip /root/redbean.com build/HTML5/*
#       - name: Upload Artifact
#         uses: actions/upload-artifact@v1
#         with:
#           name: HTML5
#           path: build/HTML5
#       - name: Upload binaries to release
#         uses: svenstaro/upload-release-action@v2
#         with:
#           repo_token: ${{ secrets.GITHUB_TOKEN }}
#           #Cannot use $EXPORT_NAME sadly
#           file: build/HTML5/libgdexample.javascript.template_debug.wasm32.wasm
#           asset_name: Gunner-continuous-build-HTML5.zip
#           tag: continuous-build
#           overwrite: true
#           body: "Bleeding edge release for those who like to live on the edge :)"
#       - name: Upload redbean binaries to release
#         uses: svenstaro/upload-release-action@v2
#         with:
#           repo_token: ${{ secrets.GITHUB_TOKEN }}
#           #Cannot use $EXPORT_NAME sadly
#           file: /root/redbean.com
#           asset_name: Gunner-continuous-build-redbean-HTML5.com
#           tag: continuous-build
#           overwrite: true
#           body: "Bleeding edge release for those who like to live on the edge :)"
#       - name: Install rsync 📚
#         run: |
#           apt-get update && apt-get install -y rsync
#       - name: Configure git to trust the workspace despite the different owner
#         run:
#           git config --global --add safe.directory "$GITHUB_WORKSPACE"
#       - name: Deploy to GitHub Pages 🚀
#         uses: JamesIves/github-pages-deploy-action@releases/v3
#         with:
#           GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
#           BRANCH: gh-pages # The branch the action should deploy to.
#           FOLDER: build/HTML5 # The folder the action should deploy.

