name: "linux build"
on: push

env:
  GODOT_VERSION: 3.4.2
  EXPORT_NAME: Gunner

jobs:
  export-linux:
    name: Linux Export
    runs-on: ubuntu-latest
    container:
      image: thebigg1/godot-ci:latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          lfs: true
      - name: Setup
        run: |
          mkdir -v -p ~/.local/share/godot/templates
          mv /root/.local/share/godot/templates/${GODOT_VERSION}.stable ~/.local/share/godot/templates/${GODOT_VERSION}.stable
      - name: Linux Build
        run: |
          mkdir -v -p build/linux
          cd $EXPORT_NAME
          godot -v --export "Linux/X11" ../build/linux/$EXPORT_NAME.x86_64
      - name: Upload Artifact
        uses: actions/upload-artifact@v1
        with:
          name: linux
          path: build/linux
      - name: Upload binaries to release
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          #Cannot use $EXPORT_NAME sadly
          file: build/linux/Gunner.x86_64
          asset_name: Gunner-continuous-release-linux.x86_64
          tag: Gunner-continuous-release
          overwrite: true
          body: "Bleeding edge release for those who like to live on the edge :)"
