name: "linux build"
on: push

env:
  GODOT_VERSION: 4.2.1
  EXPORT_NAME: Gunner

jobs:
  export-linux:
    name: Linux Export
    runs-on: ubuntu-latest
    container:
      image: thebigg1/godot-ci:v4.2.1.stable.official_b09f793f5
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          lfs: true
      - name: Coding Style
        run: |
          make format
      - name: Setup
        run: |
          mkdir -v -p ~/.local/share/godot/export_templates
          mv /root/.local/share/godot/export_templates/${GODOT_VERSION}.stable ~/.local/share/godot/export_templates/${GODOT_VERSION}.stable
      - name: Install Godot Modules
        run: make get_gdext_modules
      - name: Linux Build
        run: |
          mkdir -v -p build/linux
          cd $EXPORT_NAME
          godot --headless -v --export-debug "Linux/X11" ../build/linux/$EXPORT_NAME.x86_64
      - name: Upload Artifact
        uses: actions/upload-artifact@v1
        with:
          name: linux
          path: build/linux
      - name: zip build
        run: |
         zip build/linux/$EXPORT_NAME.zip build/linux/*
      - name: Upload binaries to release
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          #Cannot use $EXPORT_NAME sadly
          file: build/linux/Gunner.zip
          asset_name: Gunner-continuous-build-linux.zip
          tag: continuous-build
          overwrite: true
          body: "Bleeding edge release for those who like to live on the edge :)"
