name: "godot-ci export"
on: push

env:
  GODOT_VERSION: 3.4
  EXPORT_NAME: Gunner

jobs:
  export-mac:
    name: Mac Export
    runs-on: ubuntu-latest
    container:
      image: thebigg1/godot-ci:latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          lfs: true
      - name: Setup
        run: |
          mkdir -v -p ~/.local/share/godot/templates
          mv /root/.local/share/godot/templates/${GODOT_VERSION}.beta ~/.local/share/godot/templates/${GODOT_VERSION}.beta
      - name: Mac Build
        run: |
          mkdir -v -p build/mac
          cd $EXPORT_NAME
          godot -v --export "Mac OSX" ../build/mac/$EXPORT_NAME.zip
      - name: Upload Artifact
        uses: actions/upload-artifact@v1
        with:
          name: mac
          path: build/mac
      - name: Upload binaries to release
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          #Cannot use $EXPORT_NAME sadly
          file: build/mac/Gunner.zip
          asset_name: Gunner-continuous-release-mac.zip
          tag: Gunner-continuous-release
          overwrite: true
          body: "Bleeding edge release for those who like to live on the edge :)"
