#Workflow based on  https://github.com/abarichello/godot-ci/blob/master/.github/workflows/godot-ci.yml

name: "windows build"
on: push

env:
  GODOT_VERSION: 4.4
  EXPORT_NAME: Gunner

jobs:
  export-windows:
    name: Windows Export
    runs-on: ubuntu-latest
    container:
      image: thebigg1/godot-ci:v4.4.stable.official_4c311cbee
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          lfs: true
      - name: Tag Repo
        uses: richardsimko/update-tag@v1
        with:
          tag_name: continuous-build
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Setup
        run: |
          mkdir -v -p ~/.local/share/godot/export_templates
          mv /root/.local/share/godot/export_templates/${GODOT_VERSION}.stable ~/.local/share/godot/export_templates/${GODOT_VERSION}.stable
      - name: Install Godot Modules
        run: make get_gdext_modules            
      - name: Windows Build
        run: |
          mkdir -v -p build/windows
          cd $EXPORT_NAME
          godot --headless -v --export-debug "Windows Desktop" ../build/windows/$EXPORT_NAME.exe
      - name: zip build
        run: |
         zip build/windows/$EXPORT_NAME.zip build/windows/*
      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: windows
          path: build/windows
      - name: Upload binaries to release
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: build/windows/Gunner.zip
          asset_name: Gunner-continuous-build-windows.zip
          tag: continuous-build
          overwrite: true
          body: "Bleeding edge release for those who like to live on the edge :)"



# The web build does not work at the moment.
#  export-web:
#    name: Web Export
#    runs-on: ubuntu-latest
#    container:
#      image: thebigg1/godot-ci:v4.4.stable.official_4c311cbee
#    steps:
#      - name: Checkout
#        uses: actions/checkout@v2
#        with:
#          lfs: true
#      - name: Setup
#        run: |
#          mkdir -v -p ~/.local/share/godot/templates
#          mv /root/.local/share/godot/templates/${GODOT_VERSION}.stable ~/.local/share/godot/templates/${GODOT_VERSION}.stable
#      - name: Web Build
#        run: |
#          mkdir -v -p build/web
#          cd $EXPORT_NAME
#          godot --headless -v --export-release "HTML5" ../build/web/index.html
#      - name: Upload Artifact
#        uses: actions/upload-artifact@v4
#        with:
#          name: web
#          path: build/web
#      - name: Upload binaries to release
#        uses: svenstaro/upload-release-action@v2
#        with:
#          repo_token: ${{ secrets.GITHUB_TOKEN }}
#          #Cannot use $EXPORT_NAME sadly
#          file: build/web/index.html
#          asset_name: Gunner-index-continuous-release-web.html
#          tag: Gunner-continuous-release
#          overwrite: true
#          body: "Bleeding edge release for those who like to live on the edge :)"
#      # Installing rsync is needed in order to deploy to GitHub Pages. Without it, the build will fail.
#      - name: Install rsync 📚
#        run: |
#          apt-get update && apt-get install -y rsync
#      - name: Deploy to GitHub Pages 🚀
#        uses: JamesIves/github-pages-deploy-action@releases/v3
#        with:
#          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
#          BRANCH: gh-pages # The branch the action should deploy to.
#          FOLDER: build/web # The folder the action should deploy.
